name: qcodes_auto
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - jupyterlab=4.0
  - numpy>=1.23,<1.27
  - scipy=1.10
  - h5py=3.8
  - pyqt
  - qtpy>=2.3,<3
  - matplotlib=3.7
  - pandas=1.5
  - xarray=2023.2
  - pyvisa>=1.12,<1.13
  - qcodes=0.37